### PR TITLE
Added a rake task to sync RBAC roles for existing workflows

### PR DESCRIPTION
**Pull request by hsong-rh**
`rake approval:sync_rbac_roles` task is added to sync RBAC roles for workflows.

### CODE REVIEW

**Comment by mkanoor** [comment]
@hsong-rh What is the use case for this is this only for development and QE as part of debugging cleanup. In real production environment we won't be able to run any rake tasks.

**Comment by hsong-rh** [comment]
@mkanoor After RBAC is enabled, approver in a certain group cannot process any requests assigned  to him, because the group he belongs to does not have role. This rake task will create roles for all such groups.

**Comment by mkanoor** [comment]
@hsong-rh After these PR's are merged wouldn't RBAC be enabled as default so this rake task is a temporary thing for QE and DEV correct?

**Comment by bzwei** [comment]
@mkanoor It is true the tool is a one time and temporary thing. It does not need to be a rake task. We just need a way to share the tool and save the source code. Any suggestion?

**Comment by mkanoor** [comment]
@bzwei @hsong-rh I think any rake task is a hack and not practical in a production containerized environment. We have a similar set to debugging rake tasks that we carry in catalog service. So for now it's ok. Maybe at some point we should start deprecating it.

**Comment by bzwei** [comment]
we can do the same thing. We can remove the task after everybody enrolls in RBAC roles.

**Pull request merged**
