### PR TITLE
Prepare Travis, CodeClimate, and deployment

### PR DESCRIPTION
**Pull request by Fryguy**
Prepare Travis, CodeClimate, and deployment

### CODE REVIEW

**Comment by Fryguy** [comment]
Ignore the codeclimate changes, because this creates the baseline.

**Comment by Fryguy** [comment]
@hsong-rh Please merge.

**Comment by hsong-rh** [comment]
@Fryguy I still cannot merge.

**Comment by Fryguy** [comment]
@hsong-rh This is good to go

**Comment by hsong-rh** [comment]
@Fryguy Great! 👍

**Comment by Fryguy** [comment]
@bzwei Please merge.

**Pull request merged**
