### PR TITLE
Improved status message in webpage approval

### PR DESCRIPTION
**Pull request by hsong-rh**
Changed to show approver's action inside the status message when approval via open link in the email.

Status message for succeeded action:
image

Status message for failed action:
image

### CODE REVIEW

**Comment by bzwei** [comment]
How about the following messages:

You just approved the request.
You just denied the request.
You just added a comment to the request.

You cannot approve the request. 
Reason:

You cannot deny the request. 
Reason:

@gmcculloug any input?

**Comment by bzwei** [comment]
@hsong-rh The hyper link text should be `details`.

**Comment by hsong-rh** [comment]
> @hsong-rh The hyper link text should be `details`.

It's changed already.

**Comment by gmcculloug** [comment]
If it is clear that we are in an approval system then it could be simplified to:

```
Your action [Approve] has been recorded.
```
and
```
Unable to complete action [Memo]
Reason: <>
```

**Pull request merged**
