### PR TITLE
Fixed code climate errors

### PR DESCRIPTION
**Pull request by hsong-rh**
https://github.com/codeclimate/codeclimate-rubocop/issues/166

### CODE REVIEW

**Comment by hsong-rh** [comment]
Only worked in my local env. Closed.

**Comment by gmcculloug** [comment]
@syncrou Should we do the same here as https://github.com/ManageIQ/catalog-api/pull/305

**Comment by syncrou** [comment]
@hsong-rh Per what @gmcculloug suggested.  Applying the fix in ManageIQ/catalog-api#305 did fix the issue for us in Catalog.

**Comment by Fryguy** [comment]
:-1: ... we should not proliferate what is in ManageIQ/catalog-api#305 as it's not maintainable from an org perspective.  Can we please discuss in the miq-bot channel?

**Comment by syncrou** [comment]
@Fryguy  per this comment, was only temporary.

https://github.com/ManageIQ/catalog-api/pull/305#issuecomment-507395730

**Pull request merged**
