### PR TITLE
Renamed operationId to avoid duplicates

### PR DESCRIPTION
**Pull request by hsong-rh**
This PR fixed two issues:
1. Removed duplicated operationId: 
    https://projects.engineering.redhat.com/browse/SSP-201
2. Added SUCCESS response for workflow's DELETE/PATCH actions: 
    https://projects.engineering.redhat.com/browse/SSP-212

### CODE REVIEW

**Comment by hsong-rh** [comment]
@bzwei Please review.

**Comment by bzwei** [comment]
@hsong-rh Why do we need to allow client to set `x-rh-identity`? If it is for developer testing purpose we should consider alternatives.

**Comment by hsong-rh** [comment]
@bzwei Yes, it's for our own client side test script. We need to set header info to make sure all endpoints working properly. The parameter is optional, means no changes in API side if not needed.

**Comment by hsong-rh** [comment]
@bzwei As discussed, I removed optional header parameter part.

**Pull request merged**
