### PR TITLE
Convert api from swagger 2.0 to openapi 3.0

### PR DESCRIPTION
**Pull request by hsong-rh**
Convert to OpenAPI 3.0

### CODE REVIEW

**Comment by hsong-rh** [comment]
@bzwei @mkanoor Please review.

**Comment by bzwei** [comment]
@hsong-rh were you able to generate an openapi client and connect to the api server?

**Comment by hsong-rh** [comment]
@bzwei No, I tested it by querying openapi.json directly via local server. Will use openapi generator to test it now.

**Comment by hsong-rh** [comment]
@bzwei I tested with openapi generated client, it works as expected.

**Pull request merged**
